// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDz5tKPNHPZfDAUfc109515NRY9Re0JzI',
    appId: '1:424834373001:web:318104ec1f3a8ab1abfd58',
    messagingSenderId: '424834373001',
    projectId: 'pocketdad-204bf',
    authDomain: 'pocketdad-204bf.firebaseapp.com',
    storageBucket: 'pocketdad-204bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7JFBF8eFsQUHXtpBf_NroauJHtKXmv5U',
    appId: '1:424834373001:android:aa91d9f85bcf208cabfd58',
    messagingSenderId: '424834373001',
    projectId: 'pocketdad-204bf',
    storageBucket: 'pocketdad-204bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAknZutdWXFnGS4eJMYvwT49E8nxJmpbhM',
    appId: '1:424834373001:ios:2879db66156cbb94abfd58',
    messagingSenderId: '424834373001',
    projectId: 'pocketdad-204bf',
    storageBucket: 'pocketdad-204bf.appspot.com',
    iosBundleId: 'com.example.pocketdad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAknZutdWXFnGS4eJMYvwT49E8nxJmpbhM',
    appId: '1:424834373001:ios:830b7eccc5a00500abfd58',
    messagingSenderId: '424834373001',
    projectId: 'pocketdad-204bf',
    storageBucket: 'pocketdad-204bf.appspot.com',
    iosBundleId: 'com.example.pocketdad.RunnerTests',
  );
}
